version: "3.2"
services:
# Radarr - https://hotio.dev/containers/radarr/
# <mkdir /volume1/docker/appdata/radarr>
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Sonarr - https://hotio.dev/containers/sonarr/
# <mkdir /volume1/docker/appdata/sonarr>
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Bazarr - https://hotio.dev/containers/bazarr/
# <mkdir /volume1/docker/appdata/bazarr>
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}/media:/data/media

# Watchtower (automatic docker container updater) - https://github.com/containrrr/watchtower
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_TIMEOUT=10s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

# Plex - https://hotio.dev/containers/plex/
# <mkdir /volume1/docker/appdata/plex>
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 32400:32400
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - ARGS=
      - DEBUG=no
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=
      - ALLOWED_NETWORKS=
      - PLEX_PASS=${PLEX_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config:rw
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw
      - /tmp:/transcode:rw
      - /dev/dri:/dev/dri

# Tautulli - https://hotio.dev/containers/tautulli/
# <mkdir /volume1/docker/appdata/tautulli>
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - ARGS=
      - DEBUG=no
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/tautulli:/config:rw

# Lidarr - https://hotio.dev/containers/lidarr/
# <mkdir /volume1/docker/appdata/lidarr>
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/lidarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Readarr - https://hotio.dev/containers/readarr/
# <mkdir /volume1/docker/appdata/readarr>
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr:nightly
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 8787:8787
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/readarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# Prowlarr - https://hotio.dev/containers/readarr/
# <mkdir /volume1/docker/appdata/prowlarr>
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:nightly 
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/prowlarr:/config
      - ${DOCKERSTORAGEDIR}:/data

# qBittorrent - https://docs.linuxserver.io/images/docker-qbittorrent
# <mkdir /volume1/docker/appdata/qbittorent>
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - WEBUI_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/qbittorrent:/config:rw
      - ${DOCKERSTORAGEDIR}/torrents:/data/torrents:rw

# NZBGet - https://hotio.dev/containers/nzbget/
# <mkdir /volume1/docker/appdata/nzbget>
  nzbget:
    container_name: nzbget
    image: ghcr.io/hotio/nzbget:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network:
      - arrNet
    ports:
      - 6789:6789/tcp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/nzbget:/config:rw
      - ${DOCKERSTORAGEDIR}/usenet:/data/usenet:rw
